sudo: false
dist: bionic

# Adapted from
# https://github.com/mratsim/Arraymancer/blob/407cae439d5f1f76431251c28a7e6fc9652444e3/.travis.yml#L66
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

cache:
  directories:
    - $HOME/.choosenim
    - $HOME/.nimble

before_install:
  - export CHANNEL=stable
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim $CHANNEL
  - nimble install nimpy

install:
  - pip install .

before_script:
  - cd examples

script:
  - python calc.py
  - python dictionary.py
